Add Instagram Logo
cssu/cssu.ca-old pull request #97
Opened 2018-07-24 00:32 UTC by AnujanM

2018-07-24 03:10 UTC, arkon requested changes

2018-07-24 03:10 UTC, arkon commented on _includes/footer.html
> +          {% if site.instagram_username %}<li style="border: #000">
You should have the icon inside the circle. This looks weird.

2018-07-24 03:10 UTC, arkon commented on _includes/footer.html
> +                <path style="fill:#FFF" d="M256,49.471c67.266,0,75.233.257,101.8,1.469,24.562,1.121,37.9,5.224,46.778,8.674a78.052,78.052,0,0,1,28.966,18.845,78.052,78.052,0,0,1,18.845,28.966c3.45,8.
Prefer just using the `fill` attribute like the other icons.

2018-07-24 03:10 UTC, arkon commented on _includes/footer.html
> +              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
You should probably resize/simplify this icon to fit the others. I can do that if you want me to.

2018-07-24 12:47 UTC, AnujanM commented on _includes/footer.html
> +              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
Yeah My SVG editing skills arn't that great (just grabbed this from Instagram's Site), if you can simplify/resize it that would be highly appreciated.

2018-07-24 12:48 UTC, AnujanM commented on _includes/footer.html
> +          {% if site.instagram_username %}<li style="border: #000">
Yeah I tried with the circle and looked a bit off but if you can make it work @arkon that would be great!

2018-07-24 14:11 UTC, ansermino commented
Please remove the twitter link as we are not currently maintaining it.

2018-07-24 14:12 UTC, ansermino requested changes
Remove twitter link

2018-07-24 22:46 UTC, arkon commented on _includes/footer.html
> +              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
Done.

2018-07-25 00:26 UTC, AnujanM commented
Awesome, thanks a lot @arkon for fixing the logo. Looks great! 👍 🥇

2018-07-25 00:26 UTC, merged